package exception;

import org.junit.Test;

import model.Calculator;

class CalculatorTestEx {

	@Test(expected = ArithmeticException.class)
	public void testDivideForException() {
		Calculator calculator = new Calculator();
		calculator.divide(9.0, 0.0);
	}

}
