package exception;

import org.junit.Test;

import model.Calculator;

class CalculatorTestEx {

	// Kiểm tra ngoại lệ ném ra có đúng hay không
	@Test(expected = ArithmeticException.class)
	public void testDivideForException() {
		Calculator calculator = new Calculator();
		calculator.divide(9, 0);
	}

}
